"""78张塔罗牌种子数据 + 预设牌阵"""
import json

# ============ 78张塔罗牌 ============
TAROT_CARDS = [
    # ===== 大阿尔卡纳 (Major Arcana) - 22张 =====
    {"name_zh": "愚者", "name_en": "The Fool", "card_type": "major", "suit": None, "number": 0,
     "keywords": "开始,自由,天真,冒险, spontaneity,新的旅程,无限可能",
     "description": "愚者代表新的开始、冒险精神和无限的可能性。他带着行囊踏上未知的旅程，对未来充满好奇和憧憬。"},
    {"name_zh": "魔术师", "name_en": "The Magician", "card_type": "major", "suit": None, "number": 1,
     "keywords": "创造力,技能,意志力,专注, manifest,资源整合,行动力",
     "description": "魔术师拥有将想法转化为现实的能力。他桌上摆着四元素的象征物，代表他掌握了将愿景变为现实的所有工具。"},
    {"name_zh": "女祭司", "name_en": "The High Priestess", "card_type": "major", "suit": None, "number": 2,
     "keywords": "直觉,潜意识,内在智慧,神秘,静待,灵性,二元性",
     "description": "女祭司端坐在两根柱子之间，象征着直觉与潜意识的力量。她提醒我们向内探索，倾听内在的声音。"},
    {"name_zh": "女皇", "name_en": "The Empress", "card_type": "major", "suit": None, "number": 3,
     "keywords": "丰饶,母性,创造力,自然,感性,滋养,美丽",
     "description": "女皇是大地的母亲，代表丰饶、创造力和感性的力量。她鼓励我们拥抱生活中的美好与富足。"},
    {"name_zh": "皇帝", "name_en": "The Emperor", "card_type": "major", "suit": None, "number": 4,
     "keywords": "权威,结构,秩序,领导力,稳定,规则,掌控",
     "description": "皇帝象征着秩序、权威和稳定的力量。他代表着结构和规则，提醒我们在混乱中建立秩序。"},
    {"name_zh": "教皇", "name_en": "The Hierophant", "card_type": "major", "suit": None, "number": 5,
     "keywords": "传统,信仰,教育,指导,制度,智慧传承,精神导师",
     "description": "教皇代表传统价值、精神指引和教育。他象征着社会规范和信仰体系，提供智慧和指导。"},
    {"name_zh": "恋人", "name_en": "The Lovers", "card_type": "major", "suit": None, "number": 6,
     "keywords": "爱情,选择,和谐,关系,价值观,结合,信任",
     "description": "恋人牌不仅代表爱情，更象征着重要的选择和价值观的抉择。它提醒我们跟随内心做出真诚的选择。"},
    {"name_zh": "战车", "name_en": "The Chariot", "card_type": "major", "suit": None, "number": 7,
     "keywords": "胜利,意志力,决心,控制,前进,克服困难,自律",
     "description": "战车代表着通过意志力和决心获得胜利。它鼓励我们掌控对立的力量，朝着目标坚定前进。"},
    {"name_zh": "力量", "name_en": "Strength", "card_type": "major", "suit": None, "number": 8,
     "keywords": "内在力量,勇气,耐心,温柔,驯服,坚韧,以柔克刚",
     "description": "力量牌展现了温柔的力量——用耐心和爱心驯服了狮子。它告诉我们要用内在的坚韧以柔克刚。"},
    {"name_zh": "隐者", "name_en": "The Hermit", "card_type": "major", "suit": None, "number": 9,
     "keywords": "内省,孤独,智慧,指引,沉思,寻找真理,心灵探索",
     "description": "隐者提着灯笼在黑暗中寻找真理。他代表内省、独处和深度思考的时期，在寂静中寻找答案。"},
    {"name_zh": "命运之轮", "name_en": "Wheel of Fortune", "card_type": "major", "suit": None, "number": 10,
     "keywords": "命运,转折,周期,机遇,变化,因果,顺应时势",
     "description": "命运之轮不停转动，象征着生命中的周期变化和机遇。它提醒我们顺应时势，把握转折点。"},
    {"name_zh": "正义", "name_en": "Justice", "card_type": "major", "suit": None, "number": 11,
     "keywords": "公平,真相,因果,平衡,法律,决策,责任",
     "description": "正义女神手持天平和剑，代表公平和真相。它提醒我们每一个决定都有后果，要对自己的行为负责。"},
    {"name_zh": "倒吊人", "name_en": "The Hanged Man", "card_type": "major", "suit": None, "number": 12,
     "keywords": "牺牲,换个角度,等待,放手,顿悟,暂停,新的视角",
     "description": "倒吊人自愿倒挂，从不同的视角看世界。它代表着必要的暂停、牺牲和通过放下获得新的洞察。"},
    {"name_zh": "死神", "name_en": "Death", "card_type": "major", "suit": None, "number": 13,
     "keywords": "结束,转变,重生,放下,蜕变,新生,自然循环",
     "description": "死神牌并非字面意义的死亡，而是象征结束和转变。旧的必须结束，新的才能开始——这是重生的前奏。"},
    {"name_zh": "节制", "name_en": "Temperance", "card_type": "major", "suit": None, "number": 14,
     "keywords": "平衡,调和,耐心,中庸,融合,适度,内在和谐",
     "description": "节制天使将水在两个杯子间调和，象征着平衡和适度。它教导我们在极端之间找到中间道路。"},
    {"name_zh": "恶魔", "name_en": "The Devil", "card_type": "major", "suit": None, "number": 15,
     "keywords": "束缚,欲望,物质主义,阴影,执着,成瘾,面对恐惧",
     "description": "恶魔牌提醒我们审视自己的束缚——那些让我们无法自由的欲望、恐惧和执念。认识到束缚是解脱的第一步。"},
    {"name_zh": "高塔", "name_en": "The Tower", "card_type": "major", "suit": None, "number": 16,
     "keywords": "突变,崩塌,启示,颠覆,觉醒,清理,重建",
     "description": "高塔被雷电击中而崩塌，象征着突然的改变和旧结构的瓦解。虽然过程痛苦，但它为真正的重建扫清障碍。"},
    {"name_zh": "星星", "name_en": "The Star", "card_type": "major", "suit": None, "number": 17,
     "keywords": "希望,疗愈,灵感,信念,宁静,指引,更新",
     "description": "星星是希望的灯塔，在经历高塔的崩塌后带来疗愈和安宁。它象征着信念的回归和灵感的涌现。"},
    {"name_zh": "月亮", "name_en": "The Moon", "card_type": "major", "suit": None, "number": 18,
     "keywords": "幻觉,恐惧,潜意识,迷惑,直觉,梦境,未知",
     "description": "月亮照亮了黑夜中的道路，但也投下了迷惑的阴影。它代表潜意识的世界，可能存在恐惧和幻觉，需要谨慎前行。"},
    {"name_zh": "太阳", "name_en": "The Sun", "card_type": "major", "suit": None, "number": 19,
     "keywords": "快乐,成功,活力,清晰,温暖,童真,积极",
     "description": "太阳是塔罗中最积极的牌之一，象征着快乐、成功和生命的活力。它驱逐一切阴霾，带来清晰和温暖。"},
    {"name_zh": "审判", "name_en": "Judgement", "card_type": "major", "suit": None, "number": 20,
     "keywords": "觉醒,召唤,重生,评估,宽恕,新阶段,内在召唤",
     "description": "天使吹响号角，灵魂从沉睡中觉醒。审判牌代表内在的召唤、自我评估和迎接人生新阶段的时刻。"},
    {"name_zh": "世界", "name_en": "The World", "card_type": "major", "suit": None, "number": 21,
     "keywords": "完成,圆满,整合,成就,旅程终点,完满,整体性",
     "description": "世界牌象征一个周期的圆满结束和整体性的达成。它是愚者之旅的终点，也是新一轮循环的开始。"},

    # ===== 权杖牌组 (Wands) - 14张 =====
    {"name_zh": "权杖王牌", "name_en": "Ace of Wands", "card_type": "minor", "suit": "权杖", "number": 1,
     "keywords": "新行动,创意,热情,启程,灵感,机会,勇气",
     "description": "权杖王牌代表新的开始、创意灵感和行动的火种。它是一个充满热情的新机会。"},
    {"name_zh": "权杖二", "name_en": "Two of Wands", "card_type": "minor", "suit": "权杖", "number": 2,
     "keywords": "规划,远见,选择,未来展望,决策,野心,掌控",
     "description": "权杖二象征着对未来的规划和展望。手中握有资源，需要考虑下一步的方向。"},
    {"name_zh": "权杖三", "name_en": "Three of Wands", "card_type": "minor", "suit": "权杖", "number": 3,
     "keywords": "扩展,远航,远见,贸易,领导力,探索,成长",
     "description": "权杖三代表着已经打好基础，正朝着更广阔的天地出发。象征着事业扩展和远见卓识。"},
    {"name_zh": "权杖四", "name_en": "Four of Wands", "card_type": "minor", "suit": "权杖", "number": 4,
     "keywords": "庆祝,稳定,和谐,成就,安居,团队,收获",
     "description": "权杖四描绘了庆祝和安居乐业的场景，象征着阶段性的成就和稳固的根基。"},
    {"name_zh": "权杖五", "name_en": "Five of Wands", "card_type": "minor", "suit": "权杖", "number": 5,
     "keywords": "竞争,冲突,挑战,磨合,多样化,辩论,激荡",
     "description": "权杖五展现了激烈的竞争和多元化的碰撞。虽然有冲突，但这种摩擦也可能激发进步。"},
    {"name_zh": "权杖六", "name_en": "Six of Wands", "card_type": "minor", "suit": "权杖", "number": 6,
     "keywords": "胜利,认可,自信,凯旋,荣誉,领导,公众赞誉",
     "description": "权杖六是胜利者的凯旋，代表着公众的认可和赞誉。努力得到了回报和肯定。"},
    {"name_zh": "权杖七", "name_en": "Seven of Wands", "card_type": "minor", "suit": "权杖", "number": 7,
     "keywords": "坚持,防守,勇气,捍卫,挑战,立场,不屈不挠",
     "description": "权杖七展现了一个人面对众多挑战时的坚定防守。它代表着坚持立场、勇敢面对困难的勇气。"},
    {"name_zh": "权杖八", "name_en": "Eight of Wands", "card_type": "minor", "suit": "权杖", "number": 8,
     "keywords": "快速,进展,行动,消息,飞速发展,畅通,势头",
     "description": "权杖八象征着事物飞速发展，障碍被清除，事情进展神速。好消息和快速的变化即将到来。"},
    {"name_zh": "权杖九", "name_en": "Nine of Wands", "card_type": "minor", "suit": "权杖", "number": 9,
     "keywords": "坚持,韧性,最后的防守,经验,毅力,警惕,准备",
     "description": "权杖九代表着经历了许多战斗后的坚韧。虽然疲惫，但仍保持警惕和坚持，最后的胜利在望。"},
    {"name_zh": "权杖十", "name_en": "Ten of Wands", "card_type": "minor", "suit": "权杖", "number": 10,
     "keywords": "负担,责任,压力,过载,完成,沉重,释放需求",
     "description": "权杖十代表承担了过多的责任和压力。虽然有能力完成，但需要学会分担和释放。"},
    {"name_zh": "权杖侍从", "name_en": "Page of Wands", "card_type": "minor", "suit": "权杖", "number": 11,
     "keywords": "探索,新消息,热情,学习,冒险精神,好奇,潜力",
     "description": "权杖侍从是一个充满热情和好奇心的探索者。他带来了新消息或新机会，鼓励我们勇敢尝试。"},
    {"name_zh": "权杖骑士", "name_en": "Knight of Wands", "card_type": "minor", "suit": "权杖", "number": 12,
     "keywords": "行动,冒险,冲动,激情,追求,进取,大胆",
     "description": "权杖骑士充满行动力和冒险精神，急于追求目标。他的热情极具感染力，但也需要警惕冲动。"},
    {"name_zh": "权杖王后", "name_en": "Queen of Wands", "card_type": "minor", "suit": "权杖", "number": 13,
     "keywords": "自信,魅力,领导,温暖,独立,创造力,感染力",
     "description": "权杖王后充满自信和魅力，善于领导和激励他人。她优雅地平衡着事业和家庭。"},
    {"name_zh": "权杖国王", "name_en": "King of Wands", "card_type": "minor", "suit": "权杖", "number": 14,
     "keywords": "领导力,远见,企业家精神,荣誉,果断,开拓,鼓舞",
     "description": "权杖国王是一位有远见的领导者，拥有创业精神和强大的执行力。他善于鼓舞人心并带领团队前进。"},

    # ===== 圣杯牌组 (Cups) - 14张 =====
    {"name_zh": "圣杯王牌", "name_en": "Ace of Cups", "card_type": "minor", "suit": "圣杯", "number": 1,
     "keywords": "新感情,爱,直觉,情感溢出,灵性开启,喜悦,丰沛",
     "description": "圣杯王牌象征着新的情感开始，爱和喜悦如泉水般涌出。它代表着心灵的丰沛和灵性的开启。"},
    {"name_zh": "圣杯二", "name_en": "Two of Cups", "card_type": "minor", "suit": "圣杯", "number": 2,
     "keywords": "伙伴关系,吸引力,平等,连接,和谐,合作,互信",
     "description": "圣杯二代表两个人的平等连接和互相吸引。无论是爱情还是合作关系，都建立在相互尊重的基础上。"},
    {"name_zh": "圣杯三", "name_en": "Three of Cups", "card_type": "minor", "suit": "圣杯", "number": 3,
     "keywords": "庆祝,友谊,欢聚,分享快乐,社交,合作,团聚",
     "description": "圣杯三是欢庆和友谊的牌，象征着朋友间的欢聚、分享快乐和彼此支持的美好时光。"},
    {"name_zh": "圣杯四", "name_en": "Four of Cups", "card_type": "minor", "suit": "圣杯", "number": 4,
     "keywords": "沉思,不满,冷漠,新机会视而不见,内省,倦怠,重新评估",
     "description": "圣杯四描绘了一个沉浸在自己的思绪中、对眼前机会视而不见的人。它提醒我们审视内心的不满来源。"},
    {"name_zh": "圣杯五", "name_en": "Five of Cups", "card_type": "minor", "suit": "圣杯", "number": 5,
     "keywords": "失落,悲伤,遗憾,关注失去,希望尚存,哀悼,转变视角",
     "description": "圣杯五展示了为失去而悲伤的时刻，但身后还有两个杯子未被看见。提醒我们在悲伤中也要看到残留的希望。"},
    {"name_zh": "圣杯六", "name_en": "Six of Cups", "card_type": "minor", "suit": "圣杯", "number": 6,
     "keywords": "回忆,怀旧,纯真,童年,善意,过往,简单快乐",
     "description": "圣杯六描绘了纯真和怀旧的场景，可能是回忆过去的美好，或是收到来自过去的善意和礼物。"},
    {"name_zh": "圣杯七", "name_en": "Seven of Cups", "card_type": "minor", "suit": "圣杯", "number": 7,
     "keywords": "幻想,选择,白日梦,诱惑,迷惑,想象力,多重选项",
     "description": "圣杯七展现了许多诱人的选项和幻想。它提醒我们在众多选择中保持清醒，辨别真实与虚幻。"},
    {"name_zh": "圣杯八", "name_en": "Eight of Cups", "card_type": "minor", "suit": "圣杯", "number": 8,
     "keywords": "离开,追寻,放弃,走向更高,情感旅程,转身,深层需求",
     "description": "圣杯八描绘了一个人离开已有的成就，踏上追寻更深层意义的旅程。代表着勇敢放下的时刻。"},
    {"name_zh": "圣杯九", "name_en": "Nine of Cups", "card_type": "minor", "suit": "圣杯", "number": 9,
     "keywords": "愿望实现,满足,快乐,自得,舒适,成就感,心想事成",
     "description": "圣杯九是愿望成真的牌。坐在九个杯子前的人面带满足的微笑，象征着心想事成和情感的满足。"},
    {"name_zh": "圣杯十", "name_en": "Ten of Cups", "card_type": "minor", "suit": "圣杯", "number": 10,
     "keywords": "圆满,家庭幸福,和谐,情感巅峰,归属,爱满,完美结局",
     "description": "圣杯十展示了情感的最高境界——家庭和睦、爱意满溢的彩虹之约。代表着情感的圆满和归属感。"},
    {"name_zh": "圣杯侍从", "name_en": "Page of Cups", "card_type": "minor", "suit": "圣杯", "number": 11,
     "keywords": "创意,直觉,情感消息,梦想,敏感,艺术灵感,温柔",
     "description": "圣杯侍从是一个充满创意和直觉的梦想家。他带来了情感方面的消息，鼓励我们追随内心的灵感。"},
    {"name_zh": "圣杯骑士", "name_en": "Knight of Cups", "card_type": "minor", "suit": "圣杯", "number": 12,
     "keywords": "浪漫,追求,理想主义,献身,魅力,艺术气质,求婚者",
     "description": "圣杯骑士是浪漫和理想的化身，他追寻梦想和爱情。他带来了浪漫的提案或艺术性的追求。"},
    {"name_zh": "圣杯王后", "name_en": "Queen of Cups", "card_type": "minor", "suit": "圣杯", "number": 13,
     "keywords": "同理心,直觉,关怀,情感深度,包容,慈爱,心灵",
     "description": "圣杯王后是情感智慧和同理心的化身。她善于倾听和理解他人的情感，用慈爱包容一切。"},
    {"name_zh": "圣杯国王", "name_en": "King of Cups", "card_type": "minor", "suit": "圣杯", "number": 14,
     "keywords": "情感成熟,宽容,外交,冷静,创造力,情绪管理,智慧",
     "description": "圣杯国王代表了情感成熟和宽容大度。他能够掌控自己的情绪，并以宽容和智慧处理人际关系。"},

    # ===== 宝剑牌组 (Swords) - 14张 =====
    {"name_zh": "宝剑王牌", "name_en": "Ace of Swords", "card_type": "minor", "suit": "宝剑", "number": 1,
     "keywords": "新思想,清晰,真理,决断,智力,突破,公正",
     "description": "宝剑王牌象征着新的思想和清晰的洞察力。如同利剑斩断迷雾，带来真理和清晰的方向。"},
    {"name_zh": "宝剑二", "name_en": "Two of Swords", "card_type": "minor", "suit": "宝剑", "number": 2,
     "keywords": "僵局,选择,逃避,平衡,封闭,两难,暂时回避",
     "description": "宝剑二描绘了一个蒙眼持双剑的人，代表着面对两难选择时的僵持和回避。需要摘下眼罩看清真相。"},
    {"name_zh": "宝剑三", "name_en": "Three of Swords", "card_type": "minor", "suit": "宝剑", "number": 3,
     "keywords": "伤心,分离,痛苦,真相刺穿,心碎,背叛,释放",
     "description": "宝剑三是一张关于心痛和悲伤的牌。三把剑刺穿心脏，象征着痛苦但必要的真相，以及情感的释放。"},
    {"name_zh": "宝剑四", "name_en": "Four of Swords", "card_type": "minor", "suit": "宝剑", "number": 4,
     "keywords": "休息,恢复,沉思,退隐,充电,暂停,冥想",
     "description": "宝剑四代表着在精神疲惫后需要的休息和恢复期。暂时的退隐和沉思是为了更好地回归。"},
    {"name_zh": "宝剑五", "name_en": "Five of Swords", "card_type": "minor", "suit": "宝剑", "number": 5,
     "keywords": "冲突,失败,空洞胜利,争执,羞辱,代价,教训",
     "description": "宝剑五描绘了冲突后的场景，有人赢了但付出了代价。它提醒我们思考：这样的胜利值得吗？"},
    {"name_zh": "宝剑六", "name_en": "Six of Swords", "card_type": "minor", "suit": "宝剑", "number": 6,
     "keywords": "过渡,疗愈,离开困境,前行,平静,搬家,心态转变",
     "description": "宝剑六象征着从困境走向平静的过渡期。虽然前路漫漫，但正在离开风暴区域，趋向安宁。"},
    {"name_zh": "宝剑七", "name_en": "Seven of Swords", "card_type": "minor", "suit": "宝剑", "number": 7,
     "keywords": "策略,隐蔽,巧妙,逃避,不诚实,独自行动,智取",
     "description": "宝剑七描绘了一个人悄悄拿走宝剑的场景。它可能代表策略和机智，也可能暗示不够光明正大的行为。"},
    {"name_zh": "宝剑八", "name_en": "Eight of Swords", "card_type": "minor", "suit": "宝剑", "number": 8,
     "keywords": "束缚,限制,自我设限,被困感,视野受限,无助,解放可能",
     "description": "宝剑八描绘了一个被剑包围、蒙住眼睛的人。虽然看似被困，但束缚很大程度上来自自我设限——其实可以挣脱。"},
    {"name_zh": "宝剑九", "name_en": "Nine of Swords", "card_type": "minor", "suit": "宝剑", "number": 9,
     "keywords": "焦虑,噩梦,担忧,失眠,恐惧,过度思虑,精神折磨",
     "description": "宝剑九展现了深夜被焦虑和噩梦困扰的场景。它代表着过度的担忧和精神上的折磨，但这种恐惧往往被放大。"},
    {"name_zh": "宝剑十", "name_en": "Ten of Swords", "card_type": "minor", "suit": "宝剑", "number": 10,
     "keywords": "结束,见底,绝境,终结,最坏已过,曙光,重生前夜",
     "description": "宝剑十是宝剑牌组的终结，十把剑插在背上，看似绝望。但黎明正在到来，事情已经无法更糟，唯有向上。"},
    {"name_zh": "宝剑侍从", "name_en": "Page of Swords", "card_type": "minor", "suit": "宝剑", "number": 11,
     "keywords": "好奇,求知,警觉,信息收集,沟通,分析,追问",
     "description": "宝剑侍从是一个思维敏捷的求知者。他代表对真相的追求、信息的收集和分析能力的运用。"},
    {"name_zh": "宝剑骑士", "name_en": "Knight of Swords", "card_type": "minor", "suit": "宝剑", "number": 12,
     "keywords": "迅速,果敢,冲锋,急切,决断力,进取,不惧挑战",
     "description": "宝剑骑士以惊人的速度冲向目标，代表着果敢的行动力和快速的思维。他勇往直前，无所畏惧。"},
    {"name_zh": "宝剑王后", "name_en": "Queen of Swords", "card_type": "minor", "suit": "宝剑", "number": 13,
     "keywords": "理性,独立,智慧,边界,经验,清晰判断,坦诚",
     "description": "宝剑王后是理性和智慧的化身。她经历过风霜，拥有独立判断力和清晰的界限感。"},
    {"name_zh": "宝剑国王", "name_en": "King of Swords", "card_type": "minor", "suit": "宝剑", "number": 14,
     "keywords": "权威,智识,分析,公正,纪律,专业性,决断",
     "description": "宝剑国王代表了智识的权威和公正的判断。他运用逻辑和分析能力做出公正的决策。"},

    # ===== 星币牌组 (Pentacles) - 14张 =====
    {"name_zh": "星币王牌", "name_en": "Ace of Pentacles", "card_type": "minor", "suit": "星币", "number": 1,
     "keywords": "新财富,机会,稳固,务实,物质开端,投资,健康",
     "description": "星币王牌代表着物质层面的新机会——可能是一份新工作、一笔投资或一个务实项目的开始。"},
    {"name_zh": "星币二", "name_en": "Two of Pentacles", "card_type": "minor", "suit": "星币", "number": 2,
     "keywords": "平衡, juggling,适应,弹性,多任务,财务管理,变通",
     "description": "星币二描绘了用∞符号连接的两个星币，代表在多种责任间寻求平衡和灵活变通的能力。"},
    {"name_zh": "星币三", "name_en": "Three of Pentacles", "card_type": "minor", "suit": "星币", "number": 3,
     "keywords": "团队合作,技艺,规划,协作,专业,建造,精益求精",
     "description": "星币三展示了团队合作和精湛技艺。它代表着分工协作、各展所长，共同建造有价值的成果。"},
    {"name_zh": "星币四", "name_en": "Four of Pentacles", "card_type": "minor", "suit": "星币", "number": 4,
     "keywords": "守财,控制,稳定,安全感,紧握,囤积,不愿放手",
     "description": "星币四描绘了一个紧抓星币不放的人。它代表了财务上的保守和对安全感的追求，但也要警惕过度控制。"},
    {"name_zh": "星币五", "name_en": "Five of Pentacles", "card_type": "minor", "suit": "星币", "number": 5,
     "keywords": "困乏,孤立,艰难,信仰危机,被排斥,求助,坚持",
     "description": "星币五展现了在风雪中艰难前行的两人。它代表物质或精神上的困乏期，但也暗示着内在的坚持和温暖之处的存在。"},
    {"name_zh": "星币六", "name_en": "Six of Pentacles", "card_type": "minor", "suit": "星币", "number": 6,
     "keywords": "给予,接受,慷慨,平衡施受,慈善,共享,公平分配",
     "description": "星币六描绘了给予者与接受者之间的平衡。它提醒我们慷慨分享，同时也学会坦然接受他人的帮助。"},
    {"name_zh": "星币七", "name_en": "Seven of Pentacles", "card_type": "minor", "suit": "星币", "number": 7,
     "keywords": "等待,评估,耐心,投资回报,成长,反思,耕耘",
     "description": "星币七展现了农人停下手头工作、审视庄稼生长的场景。它代表了耐心等待和评估投资回报的时刻。"},
    {"name_zh": "星币八", "name_en": "Eight of Pentacles", "card_type": "minor", "suit": "星币", "number": 8,
     "keywords": "精进,专注,技艺,勤奋,重复练习,工匠精神,打磨",
     "description": "星币八描绘了一个专心致志打磨星币的工匠。它代表着专注、勤奋和对技艺的精益求精。"},
    {"name_zh": "星币九", "name_en": "Nine of Pentacles", "card_type": "minor", "suit": "星币", "number": 9,
     "keywords": "独立,富足,优雅,自给自足,享受成果,品位,从容",
     "description": "星币九展示了一位在美丽花园中从容自处的女士。她代表独立自足、优雅从容地享受自己努力成果的状态。"},
    {"name_zh": "星币十", "name_en": "Ten of Pentacles", "card_type": "minor", "suit": "星币", "number": 10,
     "keywords": "财富,传承,家族,长久,稳定,繁荣,根基深厚",
     "description": "星币十代表着物质财富的积累和家族传承。它象征着长久的繁荣和稳固的根基。"},
    {"name_zh": "星币侍从", "name_en": "Page of Pentacles", "card_type": "minor", "suit": "星币", "number": 11,
     "keywords": "学习,务实,新技能,勤勉,踏实,积累,学生心态",
     "description": "星币侍从是一个踏实的学习者，专注于新技能和知识的积累。他带来了务实进步的消息。"},
    {"name_zh": "星币骑士", "name_en": "Knight of Pentacles", "card_type": "minor", "suit": "星币", "number": 12,
     "keywords": "稳重,可靠,耐心,务实,坚持,责任感,稳步前进",
     "description": "星币骑士是所有骑士中最稳健的一位。他脚踏实地，一步一个脚印地朝着目标前进，虽然慢但极其可靠。"},
    {"name_zh": "星币王后", "name_en": "Queen of Pentacles", "card_type": "minor", "suit": "星币", "number": 13,
     "keywords": "滋养,务实,富足,照顾,接地气,慷慨,管家精神",
     "description": "星币王后是一位务实而慷慨的管理者。她善于将资源转化为舒适的生活，并以滋养的方式照顾身边人。"},
    {"name_zh": "星币国王", "name_en": "King of Pentacles", "card_type": "minor", "suit": "星币", "number": 14,
     "keywords": "财富,成功,稳健,商业头脑,可靠,实力,安全感",
     "description": "星币国王是物质世界最成功的典范。他拥有雄厚的实力、卓越的商业头脑和可靠稳妥的品格。"},
]

# ============ 预设牌阵 ============
PRESET_SPREADS = [
    {
        "name": "单牌阵",
        "description": "最简洁的牌阵，适合快速获取对一个问题的直接指引。",
        "is_preset": True,
        "layout_type": "single",
        "positions": json.dumps([
            {"index": 1, "name": "核心指引", "meaning": "针对问题的核心指引和答案"}
        ])
    },
    {
        "name": "三牌阵（时间线）",
        "description": "过去、现在、未来的经典三牌阵，适合了解问题的发展脉络。",
        "is_preset": True,
        "layout_type": "timeline",
        "positions": json.dumps([
            {"index": 1, "name": "过去", "meaning": "影响当前问题的过去因素"},
            {"index": 2, "name": "现在", "meaning": "当前状况和核心问题"},
            {"index": 3, "name": "未来", "meaning": "可能的发展方向和结果"}
        ])
    },
    {
        "name": "三牌阵（身心灵）",
        "description": "从身体、心智、灵魂三个层面审视问题。",
        "is_preset": True,
        "layout_type": "stack",
        "positions": json.dumps([
            {"index": 1, "name": "身体/物质", "meaning": "物质层面、行动、环境因素"},
            {"index": 2, "name": "心智/思维", "meaning": "想法、信念、心智模式"},
            {"index": 3, "name": "灵魂/情感", "meaning": "深层情感、灵魂需求、潜意识"}
        ])
    },
    {
        "name": "凯尔特十字阵",
        "description": "塔罗最经典的十牌阵，深度剖析问题的各个维度，适合重大问题。",
        "is_preset": True,
        "layout_type": "celtic-cross",
        "positions": json.dumps([
            {"index": 1, "name": "现状", "meaning": "当前状况的核心"},
            {"index": 2, "name": "阻碍/助力", "meaning": "横跨的挑战或助力"},
            {"index": 3, "name": "根源", "meaning": "问题的基础和深层原因"},
            {"index": 4, "name": "过去", "meaning": "刚过去的影响因素"},
            {"index": 5, "name": "目标/上方", "meaning": "潜在的目标和最佳可能"},
            {"index": 6, "name": "近未来", "meaning": "即将到来的影响"},
            {"index": 7, "name": "自我", "meaning": "你的态度和立场"},
            {"index": 8, "name": "环境", "meaning": "外部环境和他人影响"},
            {"index": 9, "name": "希望与恐惧", "meaning": "内心的希望和恐惧"},
            {"index": 10, "name": "最终结果", "meaning": "综合所有因素后的可能结果"}
        ])
    },
    {
        "name": "六芒星阵",
        "description": "七张牌的星形牌阵，全面分析问题的各个层面。",
        "is_preset": True,
        "layout_type": "hexagram",
        "positions": json.dumps([
            {"index": 1, "name": "过去", "meaning": "问题的起源和背景"},
            {"index": 2, "name": "现在", "meaning": "当前核心状况"},
            {"index": 3, "name": "未来", "meaning": "发展趋势"},
            {"index": 4, "name": "对策", "meaning": "应对策略和建议"},
            {"index": 5, "name": "环境", "meaning": "周围环境和他人态度"},
            {"index": 6, "name": "希望/恐惧", "meaning": "内心的期望或担忧"},
            {"index": 7, "name": "结果", "meaning": "最终可能的结果"}
        ])
    },
    {
        "name": "二选一阵",
        "description": "当你面临两个选择时，帮助分析两条不同路径的前景。",
        "is_preset": True,
        "layout_type": "branch",
        "positions": json.dumps([
            {"index": 1, "name": "当前状况", "meaning": "问题的核心和现状"},
            {"index": 2, "name": "选择A的路径", "meaning": "第一个选项可能带来的发展"},
            {"index": 3, "name": "选择B的路径", "meaning": "第二个选项可能带来的发展"},
            {"index": 4, "name": "选择A的结果", "meaning": "第一个选项最终可能的结果"},
            {"index": 5, "name": "选择B的结果", "meaning": "第二个选项最终可能的结果"}
        ])
    },
    {
        "name": "关系牌阵",
        "description": "专门用于分析人际关系、感情和合作的六牌阵。",
        "is_preset": True,
        "layout_type": "relationship",
        "positions": json.dumps([
            {"index": 1, "name": "你", "meaning": "你在这段关系中的状态和感受"},
            {"index": 2, "name": "对方", "meaning": "对方在这段关系中的状态和感受"},
            {"index": 3, "name": "连接", "meaning": "你们之间的连接和互动模式"},
            {"index": 4, "name": "挑战", "meaning": "关系中面临的挑战"},
            {"index": 5, "name": "潜力", "meaning": "这段关系的潜力和发展方向"},
            {"index": 6, "name": "建议", "meaning": "给你的行动建议"}
        ])
    },
]


def get_card_seed_data():
    """获取78张牌种子数据"""
    return TAROT_CARDS


def get_preset_spreads():
    """获取预设牌阵"""
    return PRESET_SPREADS
